services:

  kafka:
    image: apache/kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    env_file:
      - .env
    
  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - ./pg_data:/var/lib/postgresql/data

  persistence:
    build:
      context: ./persistence
      dockerfile: Dockerfile
    container_name: persistence
    depends_on:
      - kafka
      - postgres
    env_file:
      - .env
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  indexer:
    build:
      context: ./indexer
      dockerfile: Dockerfile
    container_name: indexer
    depends_on:
      - kafka
      - persistence
    env_file:
      - .env
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  postgres_data:
