[project]
name = "stream-event-pipeline"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "kafka>=1.3.5",
    "loguru>=0.7.3",
    "psycopg2>=2.9.10",
    "python-dotenv>=1.1.0",
    "web3>=7.10.0",
]
