[project]
name = "indexer"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "dotenv>=0.9.9",
    "kafka>=1.3.5",
    "kafka-python>=2.1.5",
    "loguru>=0.7.3",
    "web3>=7.10.0",
]
